// Code generated by danmuji — DO NOT EDIT.

package coord

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"sync"
	"testing"
)

// MutatePlan must apply a read-modify-write under optimistic concurrency
// (CAS + retry), so many agents updating different parts of the same plan at
// the same time never silently clobber each other — the lost-update class the
// plain UpdateRef path allows. Eight agents are released through a barrier so
// they collide in the same window; a blind last-write-wins implementation drops
// updates here, a CAS+retry implementation does not.
func TestCoordinatorMutatePlan(t *testing.T) {
//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:15
	t.Parallel()
	//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:16
t.Run("a plan with eight pending steps", func(t *testing.T) {
		c := newTestCoordinator(t)
		steps := make([]PlanStep, 8)
		for i := range steps {
			steps[i] = PlanStep{ID: fmt.Sprintf("s%d", i), Description: "step", Status: "pending"}
		}
		createErr := c.CreatePlan(&Plan{ID: "p1", Title: "concurrency", Status: "active", Steps: steps})

		//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:24
t.Run("eight agents each complete one step, released together", func(t *testing.T) {
			release := make(chan struct{})
			var wg sync.WaitGroup
			wg.Add(8)
			for i := 0; i < 8; i++ {
				go func(idx int) {
					defer wg.Done()
					<-release
					_ = c.MutatePlan("p1", func(p *Plan) error {
						p.Steps[idx].Status = "completed"
						return nil
					})
				}(i)
			}
			close(release)
			wg.Wait()

			got, getErr := c.GetPlan("p1")
			completed := 0
			for _, s := range got.Steps {
				if s.Status == "completed" {
					completed++
				}
			}

			//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:49
t.Run("no update was lost: all eight steps are completed", func(t *testing.T) {
				//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:50
assert.Nil(t, createErr, "danmuji:50: given a plan with eight pending steps > when eight agents each complete one step, released together > then no update was lost: all eight steps are completed | expect (expect createErr == nil)")
				//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:51
assert.Nil(t, getErr, "danmuji:51: given a plan with eight pending steps > when eight agents each complete one step, released together > then no update was lost: all eight steps are completed | expect (expect getErr == nil)")
				//line /home/draco/work/graft/pkg/coord/plan_concurrency.dmj:52
assert.EqualValues(t, 8, completed, "danmuji:52: given a plan with eight pending steps > when eight agents each complete one step, released together > then no update was lost: all eight steps are completed | expect (expect completed == 8)")
			})
		})
	})
}

