// Code generated by danmuji — DO NOT EDIT.

package coord

import (
	"github.com/odvcencio/graft/pkg/object"
	"github.com/stretchr/testify/assert"
	"testing"
)

// PushCoordRefs must push the FULL coord object closure (the entire feed chain,
// not just the head blob) to the remote and CAS-update the coord refs there. A
// transport that pushes only the ref tips would land the head and leave the
// peer's feed truncated.
func TestCoordinatorPushCoordRefs(t *testing.T) {
//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:13
	t.Parallel()
	//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:14
	t.Run("a three-event feed and then a configured remote", func(t *testing.T) {
		f, ts := newFakeOrchard(t)
		defer ts.Close()
		c := newTestCoordinator(t)
		_ = c.AppendFeed(FeedEvent{Event: "e1", AgentID: "a"})
		_ = c.AppendFeed(FeedEvent{Event: "e2", AgentID: "a"})
		_ = c.AppendFeed(FeedEvent{Event: "e3", AgentID: "a"})
		setRemoteErr := c.Repo.SetRemote("origin", f.baseURL(ts))

		//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:23
		t.Run("pushing coord refs to the remote", func(t *testing.T) {
			pushErr := c.PushCoordRefs()

			walked, _ := c.WalkFeed("", 100)
			allChainOnRemote := true
			for _, ev := range walked {
				if !f.hasObject(object.Hash(ev.FeedHash)) {
					allChainOnRemote = false
				}
			}
			headSetRemotely := f.refHash("coord/feed/head") != object.Hash("")

			//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:35
			t.Run("the full feed chain transferred and the head ref is set remotely", func(t *testing.T) {
				//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:36
				assert.Nil(t, setRemoteErr, "danmuji:36: given a three-event feed and then a configured remote > when pushing coord refs to the remote > then the full feed chain transferred and the head ref is set remotely | expect (expect setRemoteErr == nil)")
				//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:37
				assert.Nil(t, pushErr, "danmuji:37: given a three-event feed and then a configured remote > when pushing coord refs to the remote > then the full feed chain transferred and the head ref is set remotely | expect (expect pushErr == nil)")
				//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:38
				assert.EqualValues(t, 3, len(walked), "danmuji:38: given a three-event feed and then a configured remote > when pushing coord refs to the remote > then the full feed chain transferred and the head ref is set remotely | expect (expect len(walked) == 3)")
				//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:39
				assert.Equal(t, true, allChainOnRemote, "danmuji:39: given a three-event feed and then a configured remote > when pushing coord refs to the remote > then the full feed chain transferred and the head ref is set remotely | expect (expect allChainOnRemote == true)")
				//line /home/draco/work/graft/pkg/coord/push_coord_refs.dmj:40
				assert.Equal(t, true, headSetRemotely, "danmuji:40: given a three-event feed and then a configured remote > when pushing coord refs to the remote > then the full feed chain transferred and the head ref is set remotely | expect (expect headSetRemotely == true)")
			})
		})
	})
}
